export enum AccountPermissionsEnum {
  TASK_CREATE_ONE = 'TASK_CREATE_ONE',
  TASK_GET_ALL = 'TASK_GET_ALL',
  TASK_GET_ONE = 'TASK_GET_ONE',
  TASK_UPDATE_ONE = 'TASK_UPDATE_ONE',
  TASK_DELETE_ONE = 'TASK_DELETE_ONE',
};
